#cp plots_Tracking_AntiS_specific/c_teff_AntiLambdaPion_RECO_eff_lxy_antiS_acceptance_distribution_and_efficiency.pdf
#cp 
array=( 
'macro_combined_FlatTree_Tracking_Skimmed_trial17_acceptance.root'
'c_teff_fractionAllEvents_numberGranddaughters_7hits_eta_antiS.pdf'
'c_teff_fractionAllEvents_numberGranddaughters_7hits_vz_antiS.pdf'
'tprof2_fractionAllEvents_numberGranddaughters_7hits_vz_lxy_antiS.pdf'

'c_h_teff_denomAntiLambdaPion_RECO_eff_lxy_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomAntiLambdaPion_RECO_eff_vz_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomAntiLambdaPion_RECO_eff_pt_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomAntiLambdaPion_RECO_eff_pz_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomAntiLambdaPion_RECO_eff_eta_antiS_acceptance_clone_distribution_and_efficiency.pdf'

'c_h_teff_denomAntiLambdaAntiProton_RECO_eff_lxy_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomAntiLambdaAntiProton_RECO_eff_vz_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomAntiLambdaAntiProton_RECO_eff_pt_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomAntiLambdaAntiProton_RECO_eff_pz_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomAntiLambdaAntiProton_RECO_eff_eta_antiS_acceptance_clone_distribution_and_efficiency.pdf'

'c_h_teff_denomKsdaugthers_RECO_eff_lxy_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomKsdaugthers_RECO_eff_vz_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomKsdaugthers_RECO_eff_pt_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomKsdaugthers_RECO_eff_pz_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomKsdaugthers_RECO_eff_eta_antiS_acceptance_clone_distribution_and_efficiency.pdf'

'c_h_teff_denomAntiLambda_RECO_eff_lxy_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomAntiLambda_RECO_eff_vz_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomAntiLambda_RECO_eff_pt_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomAntiLambda_RECO_eff_pz_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomAntiLambda_RECO_eff_eta_antiS_acceptance_clone_distribution_and_efficiency.pdf'

'c_h_teff_denomKs_RECO_eff_lxy_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomKs_RECO_eff_vz_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomKs_RECO_eff_pt_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomKs_RECO_eff_pz_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomKs_RECO_eff_eta_antiS_acceptance_clone_distribution_and_efficiency.pdf'

'c_h_teff_denomAntiS_RECO_eff_lxy_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomAntiS_RECO_eff_vz_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomAntiS_RECO_eff_pt_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomAntiS_RECO_eff_pz_antiS_acceptance_clone_distribution_and_efficiency.pdf'
'c_h_teff_denomAntiS_RECO_eff_eta_antiS_acceptance_clone_distribution_and_efficiency.pdf'


'c_h_teff_denomAntiS_RECO_eff_pt_antiS_clone_passed.pdf'
'c_h_teff_denomAntiS_RECO_eff_pz_antiS_clone_passed.pdf'
'c_h_teff_denomAntiS_RECO_eff_eta_antiS_antiS_clone_passed.pdf'
'c_h_teff_denomAntiS_RECO_eff_lxy_antiS_clone_passed.pdf'
'c_h_teff_denomAntiS_RECO_eff_vz_antiS_clone_passed.pdf'
'c_h_AntiSGrandDaughter_pt_1.pdf'
'c_h_AntiSGrandDaughter_pz_1.pdf'
'c_h_AntiSGrandDaughter_lxy_1.pdf'
'c_h_AntiSGrandDaughter_vz_1.pdf'
'c_h_AntiSGrandDaughter_dxy_1.pdf'
'c_h_AntiSGrandDaughter_dz_1.pdf'
'c_h1_AntiS_RECO_Acc_eta.pdf'
'c_h1_AntiS_RECO_Acc_lxy.pdf'
'c_h1_AntiS_RECO_Acc_phi.pdf'
'c_h1_AntiS_RECO_Acc_pt.pdf'
'c_h1_AntiS_RECO_Acc_pz.pdf'
'c_h1_AntiS_RECO_Acc_vz.pdf'
'c_h_AntiS_massMinusNeutron.pdf'
'c_h_GENRECO_matcher1_AntiLambda.pdf'
'c_h_GENRECO_matcher1_antiS.pdf'
'c_h_GENRECO_matcher1_Ks.pdf'
'c_h_GENRECO_matcher2_AntiLambda.pdf'
'c_h_GENRECO_matcher2_antiS.pdf'
'c_h_GENRECO_matcher2_Ks.pdf'
'h2_allTracksMoreThan6Hits_efficiency.pdf'

'h2_teff_nomAntiS_RECO_eff_lxy_antiS.pdf'
'h2_teff_nomKs_RECO_eff_vz_lxy_antiS.pdf'
'h2_teff_nomAntiLambda_RECO_eff_vz_lxy_antiS.pdf'
'h2_teff_nomKsdaughters_RECO_eff_vz_lxy_antiS.pdf'
'h2_teff_nomAntiLambdaPion_RECO_eff_vz_lxy_antiS.pdf'
'h2_teff_nomAntiLambdaAntiProton_RECO_eff_vz_lxy_antiS.pdf'

'c_h_teff_denomAntiS_RECO_eff_lxy_antiS_reco_clone_passed.pdf'
'c_h_teff_denomAntiS_RECO_eff_vz_antiS_reco_clone_passed.pdf'

)

source_dir="plots_Tracking_AntiS_specific/"
dest_dir="plots_Tracking_AntiS_specific_important/"

for i in "${array[@]}"
do
	cp $source_dir$i $dest_dir
done
